-- Drop all existing tables and types first
DROP TABLE IF EXISTS "Integration" CASCADE;
DROP TABLE IF EXISTS "Alert" CASCADE;
DROP TABLE IF EXISTS "Forecast" CASCADE;
DROP TABLE IF EXISTS "FinancialSnapshot" CASCADE;
DROP TABLE IF EXISTS "RevenueStream" CASCADE;
DROP TABLE IF EXISTS "Customer" CASCADE;
DROP TABLE IF EXISTS "Department" CASCADE;
DROP TABLE IF EXISTS "Transaction" CASCADE;
DROP TABLE IF EXISTS "Category" CASCADE;
DROP TABLE IF EXISTS "BankAccount" CASCADE;
DROP TABLE IF EXISTS "PlaidItem" CASCADE;
DROP TABLE IF EXISTS "Company" CASCADE;
DROP TABLE IF EXISTS "Session" CASCADE;
DROP TABLE IF EXISTS "Account" CASCADE;
DROP TABLE IF EXISTS "VerificationToken" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

-- Drop all existing types
DROP TYPE IF EXISTS "IntegrationStatus" CASCADE;
DROP TYPE IF EXISTS "IntegrationType" CASCADE;
DROP TYPE IF EXISTS "AlertSeverity" CASCADE;
DROP TYPE IF EXISTS "AlertType" CASCADE;
DROP TYPE IF EXISTS "ForecastMethod" CASCADE;
DROP TYPE IF EXISTS "ForecastType" CASCADE;
DROP TYPE IF EXISTS "RevenueStatus" CASCADE;
DROP TYPE IF EXISTS "RecurringInterval" CASCADE;
DROP TYPE IF EXISTS "RevenueSourceType" CASCADE;
DROP TYPE IF EXISTS "CustomerStatus" CASCADE;
DROP TYPE IF EXISTS "CategoryType" CASCADE;
DROP TYPE IF EXISTS "PlaidItemStatus" CASCADE;
DROP TYPE IF EXISTS "AccountType" CASCADE;
DROP TYPE IF EXISTS "CompanyStage" CASCADE;
DROP TYPE IF EXISTS "UserRole" CASCADE;
